name: MyFirstPlugin
version: '${project.version}'
main: me.lucas.myfirstplugin.SurvivalGamePlugin
api-version: '1.20'
commands:
  sgame:
    description: Starts the survival game
    usage: /<command>

